# Generated by Django 3.2.12 on 2022-10-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrypt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passWord',
            field=models.CharField(max_length=100),
        ),
    ]
